# Site settings
title: P.O.V. Creative Media
email: info@povcm.com
phone: 787-523-5289
phone-alt-1: 787-368-5854
phone-alt-2: 347-306-9570
description: > # this means to ignore newlines until "baseurl:"
  <span>P.O.V. Creative Media</span> is your one-stop production boutique. Need something great? Go ahead, contact us.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://povcm.com" # the base hostname & protocol for your site
facebook_username: POVCreativeMedia

# Build settings
markdown: kramdown
exclude: [/node_modules/, /src/, /*.json, /*.md, /LICENSE]

sass:
  sourcemap: true

collections:
  works:
    title: Our Stuff
  bios:
    title: The Crew